notifications:
  email: false

dist: xenial

language: python
python:
  - '3.7'

env:
  - PYVER=37

script:
  - pip install codecov
  - coverage run -m test

after_success:
  - codecov

deploy:
  provider: pypi
  user: 'isac322'
  password:
    secure: 'STBWspgqmkEzx29C03ttdiCj+bnLRyls/5bsbY678a1Xw0ULIMTjuqu/CyDFY/8RrEKpvOTD51cu4U5c1R4mY391NO5k4bnPSopr3xglAFbg9IdqaT/VFa6s49gmUzRabdriLvgrmA1Xh38ZKDCc4xdslyc3xjZf1w4PZMoKIGe0lhuH2vc3QKg8iy8to4IVtoh1paZBY40ZisbStJYOC7fJI3Yd59qGsHs3AncU4BJitNlzPgLbLS7yeV3fBCiFEd50aCpb4I8GFpa6HXf+KkAPMmstaNVoCrtVTVQ7zKUfwaTYARu0qz4oeeFr36B4yB0CN/2KaYeaH2po5Jbg1fG025zkT1RyeE/bAt3s1jtxC+3ba5u42Fw4if1cwZtQSIXqypYCDlBLzhs85BtWUVrZesR65LyIE3EyvAE6GKNtALXNOjM7zCt8B9V6R73NZGZNPV+W7D41fe/VWci9B4F6A8R3j6cy0CgcJNQ6BMeK5RGVM4z1d8LvtIVoZ/E0iM4KOloB7n9Xdw4IVW7zO+w7mgyFBoln3FXirgJABJXerNFRfnlTSjF/8VsLZRH3AeRQPrD016Ndo8GEvgwxS/nWexndIV9zJfA9J4geF1g1gc5Uq8aVQkeBqNtCS4lLvF9PT6x1gND3yvveSAIkTs9ommavT8Wp5N4fAfPants='
  on:
    all_branches: true
  distributions: 'sdist bdist_wheel --python-tag=py${PYVER}'
  skip_cleanup: true
  skip_existing: true